### PR TITLE
Isseu #73 - Fixed list of projects rendering multiple times

### PR DESCRIPTION
**Pull request by adrianmarinwork**
The problem was that the list of projects was rendering two times creating two list of projects.
Now the list should only be rendered one time in any case.

### CODE REVIEW

**Comment by Abir-Tx** [comment]
@killerclaws12  have you tested the PR before merging ? I am still having the duplicate issue after the merge.

**Comment by adrianmarinwork** [comment]
Really? It's pretty strange after all the testing that I did and even the preview of the merge that vercel bot let you see works fine.
I'm entering the webpage and the projects page does not have duplicates.
Maybe you have the page saved in cache and thats why it's not loading the changes?

**Comment by Abir-Tx** [comment]
> Really? It's pretty strange after all the testing that I did and even the preview of the merge that vercel bot let you see works fine. I'm entering the webpage and the projects page does not have duplicates. Maybe you have the page saved in cache and that's why it's not loading the changes? Try to hard reload the page

Yeah I thought of that a while ago. I will refresh the cache & let you know if that worked or not when I go home.

**Comment by killerclaws12** [comment]
> @killerclaws12 have you tested the PR before merging ? I am still having the duplicate issue after the merge.

For me, it works perfectly fine! Maybe its your browser?

**Pull request merged**
