### PR TITLE
[Improvement] Addition of page transition for the whole site

### PR DESCRIPTION
**Pull request by Abir-Tx**
As currently our website page transition happens without any effect or animation, I am planning to add some transition effects to the website. This **PR** -

- Adds page transition to every page of ghosty-web
- Adds small animations to some div/layout changes

### CODE REVIEW

**Comment by Abir-Tx** [comment]
@GhostyORG/team-ghostyweb anyone of you familiar with **Framer Motion**? So that you could work along with me on this PR

**Comment by virtual-designer** [comment]
> @GhostyORG/team-ghostyweb anyone of you familiar with **Framer Motion**? So that you could work along with me on this PR

Yep, I can.

**Comment by killerclaws12** [comment]
Merge when you can! Try not to leave PR's open for ever!

**Comment by killerclaws12** [comment]
Also I can too!

**Comment by Abir-Tx** [comment]
> > @GhostyORG/team-ghostyweb anyone of you familiar with **Framer Motion**? So that you could work along with me on this PR
> 
> Yep, I can.

Great. You can then add some animations to element changes perhaps

**Comment by Abir-Tx** [comment]
> Merge when you can! Try not to leave PR's open for ever!

It's currently in draft stage you can see. Obviously we will merge whenever appropriate changes is done pushing related to the PR.

**Comment by virtual-designer** [comment]
> > > @GhostyORG/team-ghostyweb anyone of you familiar with **Framer Motion**? So that you could work along with me on this PR
> > 
> > 
> > Yep, I can.
> 
> Great. You can then add some animations to element changes perhaps

What do you mean by "element changes"? Sorry I could not understand.

**Comment by killerclaws12** [comment]
I think he meant transitions?

**Comment by Abir-Tx** [comment]
> What do you mean by "element changes"? I mean which element will change? Sorry I could not understand.

Ah my bad. I just simply meant to add animation/transitions anywhere possible besides page transitions. Cause framer motion can do some pretty awesome animations to layout changes or to div elements you know

**Comment by Abir-Tx** [comment]
@killerclaws12  do you like the quick fade in fade out effect or I should add some other transition effect ?

**Comment by virtual-designer** [comment]
Okay, got it. I'll add some transition effects soon

**Comment by killerclaws12** [comment]
> 

Were fine for now on the effects. I like them.

**Comment by killerclaws12** [comment]
> Okay, got it. I'll add some transition effects soon

Dont do that! We are good for now.

**Review by killerclaws12 — APPROVED** [review]

**Comment by killerclaws12** [comment]
It says this branch has conflict. Package-lock.json

**Comment by Abir-Tx** [comment]
> It says this branch has conflict. Package-lock.json

I will fix it. BTW, @killerclaws12 How's it now let me know. If ok then I will merge maybe

**Comment by killerclaws12** [comment]
> > It says this branch has conflict. Package-lock.json
> 
> I will fix it. BTW, @killerclaws12 How's it now let me know. If ok then I will merge maybe

Its alright, I reviewed and pressed approve review.

**Review by killerclaws12 — APPROVED** [review]
approved the review.

**Comment by Abir-Tx** [comment]
> approved the review.

Alright Merging

**Pull request merged**
