### PR TITLE
feat: halloween theme

### PR DESCRIPTION
**Pull request by virtual-designer**
Halloween theme.
This PR has some merge conflicts by the way.

### CODE REVIEW

**Comment by killerclaws12** [comment]
@Abir-Tx

**Comment by Abir-Tx** [comment]
Okay ! Now your changes are replacing the #38 changes :)

**Comment by virtual-designer** [comment]
> Okay ! Now your changes are replacing the #38 changes :)

I've fixed the merge conflicts. Check the preview.

**Review by Abir-Tx — COMMENTED** [review]
Done ✅

**Review by Abir-Tx — APPROVED** [review]

**Pull request merged**
