### PR TITLE
Documentation [SUGGESTION]

### PR DESCRIPTION
**Pull request by killerclaws12**
Maybe add the newer docs into the main branch which is "react" or "main" i believe. So when people look at the repo, they can see the new docs without having to switch branches to see it.

### CODE REVIEW

**Comment by Abir-Tx** [comment]
yeah of course I planned to merge it. But can you add the appropriate links to the **CONTRIBUTE.md** file which I have left blank or maybe assign someone else if possible @killerclaws12

**Comment by killerclaws12** [comment]
I dont see a empty CONTRIBUT.md file. Maybe direct me to the branch and maybe i can find it there?

**Comment by killerclaws12** [comment]
contribute.md*

**Review by Abir-Tx — APPROVED** [review]

**Comment by Abir-Tx** [comment]
@killerclaws12  NVM I have done it

**Review by Abir-Tx — APPROVED** [review]
Every links are working

**Pull request merged**
